<?php
$components = [
    "css"=>[
        [
            "title"=>"Bootstrap",
            "link"=>"https://v4-alpha.getbootstrap.com/components/navbar/",
            "href"=>$base."css/bootstrap.css",
            "type"=>"text/css",
            "media"=>"all",
            "rel"=>"stylesheet",
        ],
        [
            "title"=>"Font Awesome",
            "link"=>"http://fontawesome.io/icons/",
            "href"=>$base."css/font-awesome.css",
            "type"=>"text/css",
            "media"=>"all",
            "rel"=>"stylesheet",
        ],
    ],
    "js"=>[
        [
            "title"=>"JQuery",
            "link"=>"http://jquery.com/",
            "src"=>$base."js/jquery-3.1.1.js",
        ],
        [
            "title"=>"Tether",
            "link"=>"http://tether.io/",
            "src"=>$base."js/tether.min.js",
        ],
        [
            "title"=>"Bootstrap",
            "link"=>"https://v4-alpha.getbootstrap.com/components/navbar/",
            "src"=>$base."js/bootstrap.js",
        ],
    ]
];